<?php
namespace WikiLingo\Plugin;

/**
 * Class Div
 * @package WikiLingo\Plugin
 */
class Div extends Base
{
	public function __construct()
	{
		$this->label = 'HTML Division';
		$this->htmlTagType = 'div';
		$this->bodyIsAutoGenerated = false;
		$this->detailedAttributes['contenteditable'] = 'true';
		$this->allowLines = true;
		$this->allowWhiteSpace = true;
	}
}
