<?php
namespace WikiLingo\Plugin;

use WikiLingo;

class flash extends Base
{
    public function __construct()
    {
        $this->label = 'Flash';
        $this->htmlTagType = 'embed';
        $this->hasHtmlBody = false;
        $this->bodyIsAutoGenerated = true;
        $this->parameters = array(
            'movie' => new Parameter('Source', 'img/emblem-multimedia.png'),
            'height' => new Parameter('Height', '480px'),
            'width' => new Parameter('Width', '640px')
        );
    }

    public function render(WikiLingo\Expression\Plugin &$plugin, &$body, &$parser)
    {
	    if ($parser->wysiwyg) {
		    $plugin->attributes['src'] = 'img/emblem-multimedia.png';
	    } else {
            $plugin->attributes['src'] = $plugin->parameter('movie');
	    }
        $plugin->attributes['width'] = $plugin->parameter('width');
        $plugin->attributes['height'] = $plugin->parameter('height');

        $flash = parent::render($plugin, $body, $parser);
	    return $flash;
    }
}

