<?php
namespace WikiLingo\Plugin;

use WikiLingo;

class flash extends Base
{
    public function __construct()
    {
        $this->label = 'Flash';
        $this->htmlTagType = 'embed';
        $this->hasHtmlBody = false;
        $this->bodyIsAutoGenerated = false;
        $this->parameters = array(
            'movie' => new Parameter('Source', 'img/emblem-multimedia.png'),
            'height' => new Parameter('Height', '480px'),
            'width' => new Parameter('Width', '640px'),
            'title' => new Parameter('Title', '')
        );
    }

    public function render(WikiLingo\Expression\Plugin &$plugin, &$body, &$parser)
    {
	    $plugin->attributes['title'] = $plugin->parameter('title');

	    if ($parser->wysiwyg) {
            $this->htmlTagType = 'img';
		    $plugin->attributes['src'] = 'img/emblem-multimedia.png';
		    $flash = parent::render($plugin, $body, $parser);
		    $this->htmlTagType = 'embed';
	    } else {
            $plugin->attributes['src'] = $plugin->parameter('movie');
		    $flash = parent::render($plugin, $body, $parser);
	    }

	    return $flash;
    }
}

