<?php
namespace WikiLingo\Plugin;

class html extends Base
{
	public function __construct()
	{
		$this->label = 'HTML Area';
		$this->htmlTagType = 'span';
		$this->bodyIsAutoGenerated = false;
		$this->detailedAttributes['contenteditable'] = 'true';
	}
}