<?php
namespace WikiLingo\Plugin;

/**
 * Class Html
 * @package WikiLingo\Plugin
 */
class Html extends Base
{
	public function __construct()
	{
		$this->label = 'HTML Area';
		$this->htmlTagType = 'span';
		$this->bodyIsAutoGenerated = false;
		$this->detailedAttributes['contenteditable'] = 'true';
	}
}