<?php
namespace WikiLingo\Plugin;

use WikiLingo;
use Types\Type;
use WikiLingo\Expression\BlockType;

/**
 * Class Toc
 * @package WikiLingo\Plugin
 */
class Toc extends Base
{
    /**
     *
     */
    public function __construct()
    {
        $this->label = 'Table of Contents';
        $this->bodyIsAutoGenerated = true;
        $this->htmlTagType = 'div';
        $this->parameters['ordered'] = new Parameter('Ordered', true);
    }

    /**
     * @param WikiLingo\Expression\Plugin $plugin
     * @param string $body
     * @param $parser
     * @return string
     */
    public function render(WikiLingo\Expression\Plugin &$plugin, &$body, &$parser)
    {
	    $result = '';
        if (!isset($parser->types['WikiLingo\Expression\BlockType\Header'])) {
	        $rendered = parent::render($plugin, $result, $parser);
	        return $rendered;
        }

        $headers =& $parser->types['WikiLingo\Expression\BlockType\Header'];
        $orderedString = $plugin->parameter('ordered');
        $ordered = $orderedString == "true";

	    $container = null;

	    foreach($headers as &$header)
	    {
		    $header->pointer = true;
		    $block =& Type::Header($header)->block;

		    if ($container === null) {
                $container = new BlockType\ListContainer($block, $ordered);
		    } else {
                $container->add(new BlockType\ListItem($container, $block));
		    }
	    }
	    $result = $container->render($parser);
	    foreach($headers as &$header)
	    {
		    $header->pointer = false;
	    }

        $rendered = parent::render($plugin, $result, $parser);
        return $rendered;
    }
}